language: python
matrix:
    include:
        - python: 3.6

install:
  # install PyTorch (CPU)
  - pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install -e .

# command to run tests
script:
  - nosetests